import { PrismaClient } from '@prisma/client';
import * as bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting seed...');

  // Hash passwords
  const demoPassword = await bcrypt.hash('demo123', 10);
  const johnPassword = await bcrypt.hash('johndoe123', 10);
  const sarahPassword = await bcrypt.hash('sarah123', 10);

  // Create users
  const demoUser = await prisma.user.upsert({
    where: { email: 'demo@invoiceflow.com' },
    update: {},
    create: {
      email: 'demo@invoiceflow.com',
      password_hash: demoPassword,
      name: 'Demo User',
    },
  });

  const johnUser = await prisma.user.upsert({
    where: { email: 'john@doe.com' },
    update: {},
    create: {
      email: 'john@doe.com',
      password_hash: johnPassword,
      name: 'John Doe',
    },
  });

  const sarahUser = await prisma.user.upsert({
    where: { email: 'sarah@techcorp.com' },
    update: {},
    create: {
      email: 'sarah@techcorp.com',
      password_hash: sarahPassword,
      name: 'Sarah Johnson',
    },
  });

  console.log('✅ Users created');

  // Create companies
  const demoCompany = await prisma.company.upsert({
    where: { id: 'demo-company-1' },
    update: {},
    create: {
      id: 'demo-company-1',
      name: 'Demo Company Ltd',
      tax_id: 'GB123456789',
      address: '123 Business Street, London, UK',
      country: 'GB',
      fiscal_year_start: 1,
      export_email: 'exports@democompany.com',
      telegram_bot_token: null,
      email_forwarding_address: 'invoices@democompany.com',
    },
  });

  const techCorp = await prisma.company.upsert({
    where: { id: 'techcorp-1' },
    update: {},
    create: {
      id: 'techcorp-1',
      name: 'TechCorp Solutions',
      tax_id: 'GB987654321',
      address: '456 Innovation Way, Manchester, UK',
      country: 'GB',
      fiscal_year_start: 4,
      export_email: 'accounting@techcorp.com',
      telegram_bot_token: null,
      email_forwarding_address: 'bills@techcorp.com',
    },
  });

  const designStudio = await prisma.company.upsert({
    where: { id: 'design-studio-1' },
    update: {},
    create: {
      id: 'design-studio-1',
      name: 'Creative Design Studio',
      tax_id: 'FR12345678901',
      address: '789 Rue de la Créativité, Paris, France',
      country: 'FR',
      fiscal_year_start: 1,
      export_email: 'finance@designstudio.fr',
      telegram_bot_token: null,
      email_forwarding_address: 'factures@designstudio.fr',
    },
  });

  console.log('✅ Companies created');

  // Create memberships
  await prisma.membership.upsert({
    where: { user_id_company_id: { user_id: demoUser.id, company_id: demoCompany.id } },
    update: {},
    create: {
      user_id: demoUser.id,
      company_id: demoCompany.id,
      role: 'admin',
    },
  });

  await prisma.membership.upsert({
    where: { user_id_company_id: { user_id: johnUser.id, company_id: demoCompany.id } },
    update: {},
    create: {
      user_id: johnUser.id,
      company_id: demoCompany.id,
      role: 'admin',
    },
  });

  await prisma.membership.upsert({
    where: { user_id_company_id: { user_id: sarahUser.id, company_id: techCorp.id } },
    update: {},
    create: {
      user_id: sarahUser.id,
      company_id: techCorp.id,
      role: 'admin',
    },
  });

  await prisma.membership.upsert({
    where: { user_id_company_id: { user_id: demoUser.id, company_id: designStudio.id } },
    update: {},
    create: {
      user_id: demoUser.id,
      company_id: designStudio.id,
      role: 'member',
    },
  });

  console.log('✅ Memberships created');

  // Create subscriptions
  await prisma.subscription.upsert({
    where: { id: 'sub-demo-1' },
    update: {},
    create: {
      id: 'sub-demo-1',
      company_id: demoCompany.id,
      stripe_customer_id: 'cus_demo123456',
      stripe_subscription_id: 'sub_demo123456',
      plan_name: 'professional',
      status: 'active',
      current_period_start: new Date('2024-01-01'),
      current_period_end: new Date('2024-02-01'),
    },
  });

  await prisma.subscription.upsert({
    where: { id: 'sub-tech-1' },
    update: {},
    create: {
      id: 'sub-tech-1',
      company_id: techCorp.id,
      stripe_customer_id: 'cus_tech789012',
      stripe_subscription_id: 'sub_tech789012',
      plan_name: 'enterprise',
      status: 'active',
      current_period_start: new Date('2024-01-15'),
      current_period_end: new Date('2024-02-15'),
    },
  });

  await prisma.subscription.upsert({
    where: { id: 'sub-design-1' },
    update: {},
    create: {
      id: 'sub-design-1',
      company_id: designStudio.id,
      stripe_customer_id: null,
      stripe_subscription_id: null,
      plan_name: 'starter',
      status: 'active',
      current_period_start: new Date('2024-01-10'),
      current_period_end: new Date('2024-02-10'),
    },
  });

  console.log('✅ Subscriptions created');

  // Sample invoice data
  const invoiceData = [
    // Demo Company - Received invoices
    {
      companyId: demoCompany.id,
      userId: demoUser.id,
      sourceChannel: 'web',
      filename: 'invoice_AWS_202401.pdf',
      mimeType: 'application/pdf',
      status: 'completed',
      confidence: 0.95,
      invoiceType: 'received',
      invoiceNumber: 'AWS-2024-001234',
      issueDate: new Date('2024-01-05'),
      dueDate: new Date('2024-02-05'),
      supplierName: 'Amazon Web Services EMEA',
      supplierTaxId: 'GB727255821',
      customerName: 'Demo Company Ltd',
      customerTaxId: 'GB123456789',
      subtotal: 2450.00,
      taxAmount: 490.00,
      totalAmount: 2940.00,
      currency: 'EUR',
      taxRate: 20.0,
      paymentMethod: 'Bank Transfer',
      category: 'Cloud Services',
      reviewStatus: 'approved',
    },
    {
      companyId: demoCompany.id,
      userId: johnUser.id,
      sourceChannel: 'telegram',
      filename: 'electricity_jan2024.pdf',
      mimeType: 'application/pdf',
      status: 'completed',
      confidence: 0.88,
      invoiceType: 'received',
      invoiceNumber: 'ELEC-2024-9876',
      issueDate: new Date('2024-01-10'),
      dueDate: new Date('2024-02-10'),
      supplierName: 'British Gas Business',
      supplierTaxId: 'GB234567890',
      customerName: 'Demo Company Ltd',
      customerTaxId: 'GB123456789',
      subtotal: 850.50,
      taxAmount: 42.53,
      totalAmount: 893.03,
      currency: 'GBP',
      taxRate: 5.0,
      paymentMethod: 'Direct Debit',
      category: 'Utilities',
      reviewStatus: 'approved',
    },
    {
      companyId: demoCompany.id,
      userId: demoUser.id,
      sourceChannel: 'email',
      filename: 'office_supplies_202401.pdf',
      mimeType: 'application/pdf',
      status: 'completed',
      confidence: 0.92,
      invoiceType: 'received',
      invoiceNumber: 'STAP-2024-556677',
      issueDate: new Date('2024-01-12'),
      dueDate: new Date('2024-02-12'),
      supplierName: 'Staples UK Ltd',
      supplierTaxId: 'GB345678901',
      customerName: 'Demo Company Ltd',
      customerTaxId: 'GB123456789',
      subtotal: 325.00,
      taxAmount: 65.00,
      totalAmount: 390.00,
      currency: 'GBP',
      taxRate: 20.0,
      paymentMethod: 'Credit Card',
      category: 'Office Supplies',
      reviewStatus: 'approved',
    },
    {
      companyId: demoCompany.id,
      userId: demoUser.id,
      sourceChannel: 'web',
      filename: 'slack_subscription_jan.pdf',
      mimeType: 'application/pdf',
      status: 'needs_review',
      confidence: 0.65,
      invoiceType: 'received',
      invoiceNumber: 'SLACK-2024-88991',
      issueDate: new Date('2024-01-15'),
      dueDate: new Date('2024-02-15'),
      supplierName: 'Slack Technologies',
      supplierTaxId: 'US123456789',
      customerName: 'Demo Company Ltd',
      customerTaxId: 'GB123456789',
      subtotal: 180.00,
      taxAmount: 36.00,
      totalAmount: 216.00,
      currency: 'USD',
      taxRate: 20.0,
      paymentMethod: 'Credit Card',
      category: 'Software',
      reviewStatus: 'pending',
    },
    // Demo Company - Issued invoices
    {
      companyId: demoCompany.id,
      userId: demoUser.id,
      sourceChannel: 'web',
      filename: 'invoice_client_acme.pdf',
      mimeType: 'application/pdf',
      status: 'completed',
      confidence: 0.98,
      invoiceType: 'issued',
      invoiceNumber: 'INV-2024-001',
      issueDate: new Date('2024-01-03'),
      dueDate: new Date('2024-02-03'),
      supplierName: 'Demo Company Ltd',
      supplierTaxId: 'GB123456789',
      customerName: 'Acme Corporation',
      customerTaxId: 'GB456789012',
      subtotal: 5000.00,
      taxAmount: 1000.00,
      totalAmount: 6000.00,
      currency: 'GBP',
      taxRate: 20.0,
      paymentMethod: 'Bank Transfer',
      category: 'Consulting Services',
      reviewStatus: 'approved',
    },
    {
      companyId: demoCompany.id,
      userId: johnUser.id,
      sourceChannel: 'web',
      filename: 'invoice_client_global.pdf',
      mimeType: 'application/pdf',
      status: 'completed',
      confidence: 0.97,
      invoiceType: 'issued',
      invoiceNumber: 'INV-2024-002',
      issueDate: new Date('2024-01-08'),
      dueDate: new Date('2024-02-08'),
      supplierName: 'Demo Company Ltd',
      supplierTaxId: 'GB123456789',
      customerName: 'Global Tech Inc',
      customerTaxId: 'GB567890123',
      subtotal: 8500.00,
      taxAmount: 1700.00,
      totalAmount: 10200.00,
      currency: 'GBP',
      taxRate: 20.0,
      paymentMethod: 'Bank Transfer',
      category: 'Development Services',
      reviewStatus: 'approved',
    },
    // TechCorp - Received invoices
    {
      companyId: techCorp.id,
      userId: sarahUser.id,
      sourceChannel: 'telegram',
      filename: 'google_workspace_jan.pdf',
      mimeType: 'application/pdf',
      status: 'completed',
      confidence: 0.94,
      invoiceType: 'received',
      invoiceNumber: 'GOOG-2024-445566',
      issueDate: new Date('2024-01-06'),
      dueDate: new Date('2024-02-06'),
      supplierName: 'Google Ireland Ltd',
      supplierTaxId: 'IE6388047V',
      customerName: 'TechCorp Solutions',
      customerTaxId: 'GB987654321',
      subtotal: 620.00,
      taxAmount: 124.00,
      totalAmount: 744.00,
      currency: 'EUR',
      taxRate: 20.0,
      paymentMethod: 'Credit Card',
      category: 'Software',
      reviewStatus: 'approved',
    },
    {
      companyId: techCorp.id,
      userId: sarahUser.id,
      sourceChannel: 'email',
      filename: 'github_enterprise_jan.pdf',
      mimeType: 'application/pdf',
      status: 'completed',
      confidence: 0.91,
      invoiceType: 'received',
      invoiceNumber: 'GH-2024-778899',
      issueDate: new Date('2024-01-11'),
      dueDate: new Date('2024-02-11'),
      supplierName: 'GitHub Inc',
      supplierTaxId: 'US987654321',
      customerName: 'TechCorp Solutions',
      customerTaxId: 'GB987654321',
      subtotal: 2100.00,
      taxAmount: 420.00,
      totalAmount: 2520.00,
      currency: 'USD',
      taxRate: 20.0,
      paymentMethod: 'Credit Card',
      category: 'Software',
      reviewStatus: 'approved',
    },
    {
      companyId: techCorp.id,
      userId: sarahUser.id,
      sourceChannel: 'web',
      filename: 'office_rent_jan2024.pdf',
      mimeType: 'application/pdf',
      status: 'needs_review',
      confidence: 0.68,
      invoiceType: 'received',
      invoiceNumber: 'RENT-2024-001',
      issueDate: new Date('2024-01-01'),
      dueDate: new Date('2024-01-31'),
      supplierName: 'Manchester Property Group',
      supplierTaxId: 'GB678901234',
      customerName: 'TechCorp Solutions',
      customerTaxId: 'GB987654321',
      subtotal: 4500.00,
      taxAmount: 900.00,
      totalAmount: 5400.00,
      currency: 'GBP',
      taxRate: 20.0,
      paymentMethod: 'Bank Transfer',
      category: 'Rent',
      reviewStatus: 'pending',
    },
    // TechCorp - Issued invoices
    {
      companyId: techCorp.id,
      userId: sarahUser.id,
      sourceChannel: 'web',
      filename: 'invoice_fintech_client.pdf',
      mimeType: 'application/pdf',
      status: 'completed',
      confidence: 0.96,
      invoiceType: 'issued',
      invoiceNumber: 'TC-2024-001',
      issueDate: new Date('2024-01-04'),
      dueDate: new Date('2024-02-04'),
      supplierName: 'TechCorp Solutions',
      supplierTaxId: 'GB987654321',
      customerName: 'FinTech Innovations Ltd',
      customerTaxId: 'GB789012345',
      subtotal: 15000.00,
      taxAmount: 3000.00,
      totalAmount: 18000.00,
      currency: 'GBP',
      taxRate: 20.0,
      paymentMethod: 'Bank Transfer',
      category: 'Software Development',
      reviewStatus: 'approved',
    },
    {
      companyId: techCorp.id,
      userId: sarahUser.id,
      sourceChannel: 'web',
      filename: 'invoice_ecommerce_client.pdf',
      mimeType: 'application/pdf',
      status: 'completed',
      confidence: 0.95,
      invoiceType: 'issued',
      invoiceNumber: 'TC-2024-002',
      issueDate: new Date('2024-01-09'),
      dueDate: new Date('2024-02-09'),
      supplierName: 'TechCorp Solutions',
      supplierTaxId: 'GB987654321',
      customerName: 'E-Shop Global',
      customerTaxId: 'GB890123456',
      subtotal: 12500.00,
      taxAmount: 2500.00,
      totalAmount: 15000.00,
      currency: 'GBP',
      taxRate: 20.0,
      paymentMethod: 'Bank Transfer',
      category: 'Consulting',
      reviewStatus: 'approved',
    },
    // Design Studio - Received invoices
    {
      companyId: designStudio.id,
      userId: demoUser.id,
      sourceChannel: 'web',
      filename: 'adobe_creative_cloud.pdf',
      mimeType: 'application/pdf',
      status: 'completed',
      confidence: 0.93,
      invoiceType: 'received',
      invoiceNumber: 'ADOBE-2024-334455',
      issueDate: new Date('2024-01-07'),
      dueDate: new Date('2024-02-07'),
      supplierName: 'Adobe Systems Ireland',
      supplierTaxId: 'IE4030471LH',
      customerName: 'Creative Design Studio',
      customerTaxId: 'FR12345678901',
      subtotal: 540.00,
      taxAmount: 108.00,
      totalAmount: 648.00,
      currency: 'EUR',
      taxRate: 20.0,
      paymentMethod: 'Credit Card',
      category: 'Software',
      reviewStatus: 'approved',
    },
    {
      companyId: designStudio.id,
      userId: demoUser.id,
      sourceChannel: 'email',
      filename: 'stock_photos_jan.pdf',
      mimeType: 'application/pdf',
      status: 'completed',
      confidence: 0.89,
      invoiceType: 'received',
      invoiceNumber: 'STOCK-2024-667788',
      issueDate: new Date('2024-01-13'),
      dueDate: new Date('2024-02-13'),
      supplierName: 'Shutterstock Ireland',
      supplierTaxId: 'IE9876543210',
      customerName: 'Creative Design Studio',
      customerTaxId: 'FR12345678901',
      subtotal: 199.00,
      taxAmount: 39.80,
      totalAmount: 238.80,
      currency: 'EUR',
      taxRate: 20.0,
      paymentMethod: 'Credit Card',
      category: 'Assets',
      reviewStatus: 'approved',
    },
    // Design Studio - Issued invoices
    {
      companyId: designStudio.id,
      userId: demoUser.id,
      sourceChannel: 'web',
      filename: 'invoice_fashion_brand.pdf',
      mimeType: 'application/pdf',
      status: 'completed',
      confidence: 0.97,
      invoiceType: 'issued',
      invoiceNumber: 'CDS-2024-001',
      issueDate: new Date('2024-01-05'),
      dueDate: new Date('2024-02-05'),
      supplierName: 'Creative Design Studio',
      supplierTaxId: 'FR12345678901',
      customerName: 'Parisian Fashion House',
      customerTaxId: 'FR98765432109',
      subtotal: 3500.00,
      taxAmount: 700.00,
      totalAmount: 4200.00,
      currency: 'EUR',
      taxRate: 20.0,
      paymentMethod: 'Bank Transfer',
      category: 'Design Services',
      reviewStatus: 'approved',
    },
    {
      companyId: designStudio.id,
      userId: demoUser.id,
      sourceChannel: 'web',
      filename: 'invoice_tech_startup.pdf',
      mimeType: 'application/pdf',
      status: 'completed',
      confidence: 0.96,
      invoiceType: 'issued',
      invoiceNumber: 'CDS-2024-002',
      issueDate: new Date('2024-01-10'),
      dueDate: new Date('2024-02-10'),
      supplierName: 'Creative Design Studio',
      supplierTaxId: 'FR12345678901',
      customerName: 'StartupTech SAS',
      customerTaxId: 'FR87654321098',
      subtotal: 2800.00,
      taxAmount: 560.00,
      totalAmount: 3360.00,
      currency: 'EUR',
      taxRate: 20.0,
      paymentMethod: 'Bank Transfer',
      category: 'Branding',
      reviewStatus: 'approved',
    },
    // Additional invoices for variety
    {
      companyId: demoCompany.id,
      userId: demoUser.id,
      sourceChannel: 'telegram',
      filename: 'internet_service_jan.pdf',
      mimeType: 'application/pdf',
      status: 'processing',
      confidence: null,
      invoiceType: 'received',
      invoiceNumber: 'BT-2024-112233',
      issueDate: new Date('2024-01-14'),
      dueDate: new Date('2024-02-14'),
      supplierName: 'BT Business',
      supplierTaxId: 'GB901234567',
      customerName: 'Demo Company Ltd',
      customerTaxId: 'GB123456789',
      subtotal: 125.00,
      taxAmount: 25.00,
      totalAmount: 150.00,
      currency: 'GBP',
      taxRate: 20.0,
      paymentMethod: 'Direct Debit',
      category: 'Telecommunications',
      reviewStatus: 'pending',
    },
    {
      companyId: demoCompany.id,
      userId: johnUser.id,
      sourceChannel: 'email',
      filename: 'marketing_tools_jan.pdf',
      mimeType: 'application/pdf',
      status: 'processing',
      confidence: null,
      invoiceType: 'received',
      invoiceNumber: 'HUB-2024-998877',
      issueDate: new Date('2024-01-16'),
      dueDate: new Date('2024-02-16'),
      supplierName: 'HubSpot Ireland',
      supplierTaxId: 'IE8976543210',
      customerName: 'Demo Company Ltd',
      customerTaxId: 'GB123456789',
      subtotal: 890.00,
      taxAmount: 178.00,
      totalAmount: 1068.00,
      currency: 'EUR',
      taxRate: 20.0,
      paymentMethod: 'Credit Card',
      category: 'Marketing',
      reviewStatus: 'pending',
    },
    {
      companyId: techCorp.id,
      userId: sarahUser.id,
      sourceChannel: 'web',
      filename: 'cleaning_service_jan.pdf',
      mimeType: 'application/pdf',
      status: 'processing',
      confidence: null,
      invoiceType: 'received',
      invoiceNumber: 'CLEAN-2024-554433',
      issueDate: new Date('2024-01-17'),
      dueDate: new Date('2024-02-17'),
      supplierName: 'Professional Cleaning Services',
      supplierTaxId: 'GB012345678',
      customerName: 'TechCorp Solutions',
      customerTaxId: 'GB987654321',
      subtotal: 280.00,
      taxAmount: 56.00,
      totalAmount: 336.00,
      currency: 'GBP',
      taxRate: 20.0,
      paymentMethod: 'Bank Transfer',
      category: 'Services',
      reviewStatus: 'pending',
    },
    {
      companyId: demoCompany.id,
      userId: demoUser.id,
      sourceChannel: 'email',
      filename: 'insurance_premium_q1.pdf',
      mimeType: 'application/pdf',
      status: 'failed',
      confidence: 0.42,
      invoiceType: 'received',
      invoiceNumber: 'INS-2024-223344',
      issueDate: new Date('2024-01-18'),
      dueDate: new Date('2024-04-18'),
      supplierName: 'Business Insurance Co',
      supplierTaxId: 'GB123456780',
      customerName: 'Demo Company Ltd',
      customerTaxId: 'GB123456789',
      subtotal: 1200.00,
      taxAmount: 0.00,
      totalAmount: 1200.00,
      currency: 'GBP',
      taxRate: 0.0,
      paymentMethod: 'Bank Transfer',
      category: 'Insurance',
      reviewStatus: 'pending',
    },
    {
      companyId: techCorp.id,
      userId: sarahUser.id,
      sourceChannel: 'telegram',
      filename: 'hardware_purchase.pdf',
      mimeType: 'application/pdf',
      status: 'failed',
      confidence: 0.38,
      invoiceType: 'received',
      invoiceNumber: 'DELL-2024-776655',
      issueDate: new Date('2024-01-19'),
      dueDate: new Date('2024-02-19'),
      supplierName: 'Dell Technologies',
      supplierTaxId: 'GB234567891',
      customerName: 'TechCorp Solutions',
      customerTaxId: 'GB987654321',
      subtotal: 3200.00,
      taxAmount: 640.00,
      totalAmount: 3840.00,
      currency: 'GBP',
      taxRate: 20.0,
      paymentMethod: 'Credit Card',
      category: 'Hardware',
      reviewStatus: 'pending',
    },
    // Additional needs_review invoices
    {
      companyId: demoCompany.id,
      userId: demoUser.id,
      sourceChannel: 'web',
      filename: 'consulting_services.pdf',
      mimeType: 'application/pdf',
      status: 'needs_review',
      confidence: 0.69,
      invoiceType: 'received',
      invoiceNumber: 'CONS-2024-445566',
      issueDate: new Date('2024-01-20'),
      dueDate: new Date('2024-02-20'),
      supplierName: 'Business Consulting Group',
      supplierTaxId: 'GB345678902',
      customerName: 'Demo Company Ltd',
      customerTaxId: 'GB123456789',
      subtotal: 1850.00,
      taxAmount: 370.00,
      totalAmount: 2220.00,
      currency: 'GBP',
      taxRate: 20.0,
      paymentMethod: 'Bank Transfer',
      category: 'Consulting',
      reviewStatus: 'pending',
    },
    {
      companyId: techCorp.id,
      userId: sarahUser.id,
      sourceChannel: 'telegram',
      filename: 'legal_fees_jan.pdf',
      mimeType: 'application/pdf',
      status: 'needs_review',
      confidence: 0.63,
      invoiceType: 'received',
      invoiceNumber: 'LAW-2024-887766',
      issueDate: new Date('2024-01-21'),
      dueDate: new Date('2024-02-21'),
      supplierName: 'Manchester Legal Partners',
      supplierTaxId: 'GB456789013',
      customerName: 'TechCorp Solutions',
      customerTaxId: 'GB987654321',
      subtotal: 2400.00,
      taxAmount: 480.00,
      totalAmount: 2880.00,
      currency: 'GBP',
      taxRate: 20.0,
      paymentMethod: 'Bank Transfer',
      category: 'Legal',
      reviewStatus: 'pending',
    },
    {
      companyId: designStudio.id,
      userId: demoUser.id,
      sourceChannel: 'email',
      filename: 'freelancer_payment.pdf',
      mimeType: 'application/pdf',
      status: 'needs_review',
      confidence: 0.61,
      invoiceType: 'received',
      invoiceNumber: 'FREE-2024-556677',
      issueDate: new Date('2024-01-22'),
      dueDate: new Date('2024-02-22'),
      supplierName: 'Freelance Designer SARL',
      supplierTaxId: 'FR76543210987',
      customerName: 'Creative Design Studio',
      customerTaxId: 'FR12345678901',
      subtotal: 1500.00,
      taxAmount: 300.00,
      totalAmount: 1800.00,
      currency: 'EUR',
      taxRate: 20.0,
      paymentMethod: 'Bank Transfer',
      category: 'Freelance',
      reviewStatus: 'pending',
    },
    {
      companyId: demoCompany.id,
      userId: johnUser.id,
      sourceChannel: 'web',
      filename: 'training_course.pdf',
      mimeType: 'application/pdf',
      status: 'needs_review',
      confidence: 0.67,
      invoiceType: 'received',
      invoiceNumber: 'TRAIN-2024-998877',
      issueDate: new Date('2024-01-23'),
      dueDate: new Date('2024-02-23'),
      supplierName: 'Professional Training Ltd',
      supplierTaxId: 'GB567890124',
      customerName: 'Demo Company Ltd',
      customerTaxId: 'GB123456789',
      subtotal: 950.00,
      taxAmount: 190.00,
      totalAmount: 1140.00,
      currency: 'GBP',
      taxRate: 20.0,
      paymentMethod: 'Credit Card',
      category: 'Training',
      reviewStatus: 'pending',
    },
    {
      companyId: techCorp.id,
      userId: sarahUser.id,
      sourceChannel: 'email',
      filename: 'security_audit.pdf',
      mimeType: 'application/pdf',
      status: 'needs_review',
      confidence: 0.66,
      invoiceType: 'received',
      invoiceNumber: 'SEC-2024-334455',
      issueDate: new Date('2024-01-24'),
      dueDate: new Date('2024-02-24'),
      supplierName: 'CyberSecurity Experts Ltd',
      supplierTaxId: 'GB678901235',
      customerName: 'TechCorp Solutions',
      customerTaxId: 'GB987654321',
      subtotal: 3500.00,
      taxAmount: 700.00,
      totalAmount: 4200.00,
      currency: 'GBP',
      taxRate: 20.0,
      paymentMethod: 'Bank Transfer',
      category: 'Security',
      reviewStatus: 'pending',
    },
    {
      companyId: designStudio.id,
      userId: demoUser.id,
      sourceChannel: 'web',
      filename: 'printer_supplies.pdf',
      mimeType: 'application/pdf',
      status: 'needs_review',
      confidence: 0.64,
      invoiceType: 'received',
      invoiceNumber: 'PRINT-2024-112233',
      issueDate: new Date('2024-01-25'),
      dueDate: new Date('2024-02-25'),
      supplierName: 'Office Print Solutions',
      supplierTaxId: 'FR65432109876',
      customerName: 'Creative Design Studio',
      customerTaxId: 'FR12345678901',
      subtotal: 285.00,
      taxAmount: 57.00,
      totalAmount: 342.00,
      currency: 'EUR',
      taxRate: 20.0,
      paymentMethod: 'Credit Card',
      category: 'Office Supplies',
      reviewStatus: 'pending',
    },
    {
      companyId: demoCompany.id,
      userId: demoUser.id,
      sourceChannel: 'telegram',
      filename: 'meeting_room_rental.pdf',
      mimeType: 'application/pdf',
      status: 'needs_review',
      confidence: 0.62,
      invoiceType: 'received',
      invoiceNumber: 'MEET-2024-667788',
      issueDate: new Date('2024-01-26'),
      dueDate: new Date('2024-02-26'),
      supplierName: 'CoWork Space Ltd',
      supplierTaxId: 'GB789012346',
      customerName: 'Demo Company Ltd',
      customerTaxId: 'GB123456789',
      subtotal: 450.00,
      taxAmount: 90.00,
      totalAmount: 540.00,
      currency: 'GBP',
      taxRate: 20.0,
      paymentMethod: 'Credit Card',
      category: 'Facilities',
      reviewStatus: 'pending',
    },
    {
      companyId: techCorp.id,
      userId: sarahUser.id,
      sourceChannel: 'web',
      filename: 'recruitment_fee.pdf',
      mimeType: 'application/pdf',
      status: 'needs_review',
      confidence: 0.68,
      invoiceType: 'received',
      invoiceNumber: 'REC-2024-445566',
      issueDate: new Date('2024-01-27'),
      dueDate: new Date('2024-02-27'),
      supplierName: 'Tech Recruiters Ltd',
      supplierTaxId: 'GB890123457',
      customerName: 'TechCorp Solutions',
      customerTaxId: 'GB987654321',
      subtotal: 5000.00,
      taxAmount: 1000.00,
      totalAmount: 6000.00,
      currency: 'GBP',
      taxRate: 20.0,
      paymentMethod: 'Bank Transfer',
      category: 'HR Services',
      reviewStatus: 'pending',
    },
  ];

  // Create documents and invoices
  for (const invoice of invoiceData) {
    const document = await prisma.document.create({
      data: {
        company_id: invoice.companyId,
        user_id: invoice.userId,
        source_channel: invoice.sourceChannel,
        original_filename: invoice.filename,
        mime_type: invoice.mimeType,
        processing_status: invoice.status,
        confidence_score: invoice.confidence,
        cloud_storage_path: `uploads/${invoice.companyId}/${Date.now()}-${invoice.filename}`,
        is_public: false,
      },
    });

    // Only create invoice if processing is not in progress or failed completely
    if (invoice.status !== 'processing') {
      await prisma.invoice.create({
        data: {
          document_id: document.id,
          company_id: invoice.companyId,
          invoice_type: invoice.invoiceType,
          invoice_number: invoice.invoiceNumber,
          issue_date: invoice.issueDate,
          due_date: invoice.dueDate,
          supplier_name: invoice.supplierName,
          supplier_tax_id: invoice.supplierTaxId,
          customer_name: invoice.customerName,
          customer_tax_id: invoice.customerTaxId,
          subtotal: invoice.subtotal,
          tax_amount: invoice.taxAmount,
          total_amount: invoice.totalAmount,
          currency: invoice.currency,
          tax_rate: invoice.taxRate,
          payment_method: invoice.paymentMethod,
          category: invoice.category,
          extraction_confidence: invoice.confidence ?? 0.5,
          review_status: invoice.reviewStatus,
        },
      });
    }
  }

  console.log('✅ Documents and invoices created');

  // Create exports
  await prisma.export.create({
    data: {
      company_id: demoCompany.id,
      export_type: 'monthly',
      period_start: new Date('2024-01-01'),
      period_end: new Date('2024-01-31'),
      record_count: 12,
      cloud_storage_path: `exports/${demoCompany.id}/2024-01-monthly.csv`,
      is_public: false,
      email_sent: true,
      email_sent_at: new Date('2024-02-01T09:00:00Z'),
    },
  });

  await prisma.export.create({
    data: {
      company_id: techCorp.id,
      export_type: 'monthly',
      period_start: new Date('2024-01-01'),
      period_end: new Date('2024-01-31'),
      record_count: 10,
      cloud_storage_path: `exports/${techCorp.id}/2024-01-monthly.csv`,
      is_public: false,
      email_sent: true,
      email_sent_at: new Date('2024-02-01T10:30:00Z'),
    },
  });

  await prisma.export.create({
    data: {
      company_id: demoCompany.id,
      export_type: 'quarterly',
      period_start: new Date('2023-10-01'),
      period_end: new Date('2023-12-31'),
      record_count: 28,
      cloud_storage_path: `exports/${demoCompany.id}/2023-Q4-quarterly.csv`,
      is_public: false,
      email_sent: true,
      email_sent_at: new Date('2024-01-05T14:00:00Z'),
    },
  });

  await prisma.export.create({
    data: {
      company_id: designStudio.id,
      export_type: 'monthly',
      period_start: new Date('2024-01-01'),
      period_end: new Date('2024-01-31'),
      record_count: 5,
      cloud_storage_path: `exports/${designStudio.id}/2024-01-monthly.csv`,
      is_public: false,
      email_sent: false,
      email_sent_at: null,
    },
  });

  console.log('✅ Exports created');

  // Create some audit logs
  const sampleInvoice = await prisma.invoice.findFirst({
    where: { company_id: demoCompany.id, review_status: 'approved' },
  });

  if (sampleInvoice) {
    await prisma.auditLog.create({
      data: {
        company_id: demoCompany.id,
        user_id: demoUser.id,
        entity_type: 'invoice',
        entity_id: sampleInvoice.id,
        action: 'review',
        old_values: JSON.stringify({ review_status: 'pending' }),
        new_values: JSON.stringify({ review_status: 'approved' }),
      },
    });
  }

  console.log('✅ Audit logs created');
  console.log('\n🎉 Seed completed successfully!');
  console.log('\n📊 Summary:');
  console.log(`- Users: ${await prisma.user.count()}`);
  console.log(`- Companies: ${await prisma.company.count()}`);
  console.log(`- Documents: ${await prisma.document.count()}`);
  console.log(`- Invoices: ${await prisma.invoice.count()}`);
  console.log(`- Exports: ${await prisma.export.count()}`);
  console.log(`- Audit Logs: ${await prisma.auditLog.count()}`);
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
